"""
Script: scale_vector_exporter_mlp.py
Module role:
    Export the fitted feature and target scaling parameters used by the
    LiteML-Edge baseline MLP pipeline to a firmware-consumable C/C++ header.

Technical summary:
    This script resolves the latest baseline-model run, loads the fitted
    MinMaxScaler objects, extracts the fixed feature-order bounds and residual
    target bounds, writes the corresponding C/C++ header, and stores a version
    manifest for traceability.

Inputs:
    - Fitted X and y scaler artifacts from the baseline model run
    - Project path and versioning utilities

Outputs:
    - scalers_exported_mlp.h
    - Version manifest for the generated scaler header

Notes:
    This script assumes the repository project structure and the referenced
    utility modules. The computational logic and export procedure are
    preserved.
"""
import joblib, numpy as np
import os, sys
from pathlib import Path

# --- Bootstrap: allows importing utils/ locally and in the runner ---
ROOT = os.environ.get("RUNNER_PROJECT_ROOT")
if not ROOT:
    HERE = Path(__file__).resolve()
    for base in [HERE, *HERE.parents, Path.cwd(), *Path.cwd().parents]:
        if (base / "utils").exists():
            ROOT = str(base); break
if ROOT and ROOT not in sys.path:
    sys.path.insert(0, ROOT)
# -----------------------------------------------------------------

from utils.global_utils.paths_mlp import PROJECT_ROOT, BASE_MODEL, SCALERS_EXPORT
from utils.global_utils.versioning import create_versioned_dir, resolve_latest, update_latest, write_manifest

# === Versioned directories for the current execution ===
run_dir = create_versioned_dir(SCALERS_EXPORT, strategy="counter")
version_path = resolve_latest(BASE_MODEL)

scaler_X_path = version_path / "environment_base_model_mlp_scaler_X.pkl"
scaler_y_path = version_path / "environment_base_model_mlp_scaler_y.pkl"

# Fixed feature/target order — Option 3 (without T_diff/H_diff) + weekday/month
features = [
    "T_out", "H_out",           # current outdoor
    "T_in_lag1", "H_in_lag1",   # indoor lag1
    "T_out_lag1", "H_out_lag1", # outdoor lag1
    "T_in_lag2", "H_in_lag2",   # indoor lag2
    "sin_hour", "cos_hour",     # cyclical hour
    "weekday", "month",         # calendar attributes
]
targets = ["T_in", "H_in"]  # channel order: 0->T, 1->H (RESIDUAL: Δ)

# Load scalers from BASE_MODEL
scaler_X = joblib.load(scaler_X_path)
scaler_y = joblib.load(scaler_y_path)

# =========================
# X scaler export (features)
# =========================
X_MIN = np.array(getattr(scaler_X, "data_min_", None), dtype=float).ravel()
X_MAX = np.array(getattr(scaler_X, "data_max_", None), dtype=float).ravel()
if X_MIN.size != len(features) or X_MAX.size != len(features):
    raise RuntimeError("Invalid X scaler: data_min_/data_max_ do not match the 12-feature specification.")

X_MIN = X_MIN.round(6)
X_MAX = X_MAX.round(6)

# feature_range (MinMaxScaler). If unavailable, assume [0,1].
try:
    xr = getattr(scaler_X, "feature_range", (0.0, 1.0))
    X_FR_LO = float(xr[0]); X_FR_HI = float(xr[1])
except Exception:
    X_FR_LO = 0.0; X_FR_HI = 1.0

# =========================================
# Y scaler export (RESIDUAL: ΔT_in, ΔH_in)
# =========================================
# Contract:
#   out[0] = ΔT_in ; out[1] = ΔH_in
# MCU:
#   Δ = inverse_scaler_y(out)
#   Tin = Tin_lag1 + ΔT ; Hin = Hin_lag1 + ΔH
DY_MIN = np.array(getattr(scaler_y, "data_min_", None), dtype=float).ravel()
DY_MAX = np.array(getattr(scaler_y, "data_max_", None), dtype=float).ravel()
if DY_MIN.size != 2 or DY_MAX.size != 2:
    raise RuntimeError("Invalid y scaler: expected data_min_/data_max_ with 2 elements (ΔT, ΔH).")

DY_MIN = DY_MIN.round(6)
DY_MAX = DY_MAX.round(6)

try:
    yr = getattr(scaler_y, "feature_range", (0.0, 1.0))
    Y_FR_LO = float(yr[0]); Y_FR_HI = float(yr[1])
except Exception:
    Y_FR_LO = 0.0; Y_FR_HI = 1.0

# =========================
# C/C++ header
# =========================
header = f"""#pragma once
// Auto-generated by the LiteML-Edge scaler exporter.
//
// Feature order (MUST match firmware window packing exactly):
// {', '.join(features)}
//
// Model output contract (RESIDUAL):
//   out[0] = ΔT_in
//   out[1] = ΔH_in
//
// MCU post-processing contract:
//   Δ = inverse_scaler_y(out)
//   Tin = Tin_lag1 + ΔT_in
//   Hin = Hin_lag1 + ΔH_in
//

static const int   K_NUM_FEATURES = {len(features)};
static const float X_MIN[{len(features)}] = {{{', '.join(map(str, X_MIN))}}};
static const float X_MAX[{len(features)}] = {{{', '.join(map(str, X_MAX))}}};

// MinMax feature_range for X normalization (if applied on MCU)
static const float X_FEATURE_RANGE_LO = {X_FR_LO:.6f}f;
static const float X_FEATURE_RANGE_HI = {X_FR_HI:.6f}f;

static const int   K_NUM_TARGETS = {len(targets)};

// Y scaler stores RESIDUAL bounds (Δ), order: ΔT_in, ΔH_in
static const float DY_MIN[{len(targets)}] = {{{', '.join(map(str, DY_MIN))}}};
static const float DY_MAX[{len(targets)}] = {{{', '.join(map(str, DY_MAX))}}};

// MinMax feature_range for Y(Δ) inverse transformation (if applied on MCU)
static const float Y_FEATURE_RANGE_LO = {Y_FR_LO:.6f}f;
static const float Y_FEATURE_RANGE_HI = {Y_FR_HI:.6f}f;

// Helpful indices to avoid accidental channel swaps
#define IDX_T 0
#define IDX_H 1
"""

out_path = run_dir / "scalers_exported_mlp.h"
out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    f.write(header)

print("[INFO] Generated file:", out_path.name)
print("[INFO] Full path:", out_path.resolve())

# === Post-execution: update 'latest' and manifest ===
try:
    update_latest(run_dir)
except Exception as _e:
    print("[WARN] Unable to update 'latest':", _e)

try:
    write_manifest(
        run_dir,
        run=str(run_dir),
        source=str(version_path),
        features=features,
        targets=targets,
        X_MIN=X_MIN.tolist(),
        X_MAX=X_MAX.tolist(),
        X_FEATURE_RANGE=[X_FR_LO, X_FR_HI],
        DY_MIN=DY_MIN.tolist(),
        DY_MAX=DY_MAX.tolist(),
        Y_FEATURE_RANGE=[Y_FR_LO, Y_FR_HI],
        contract="residual_no_calibration_no_head_gain",
    )
except Exception as _e:
    print("[WARN] Unable to write manifest.json:", _e)