#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
pio_pull_headers.py — Copies headers (*.h) generated by the ML pipeline into the PlatformIO project.

What does it do?
- Copies **one or more** .h files from a *run* directory into **firmware/include/**
- Creates **per-folder versioning**, saving snapshots under
  `include/<subfolder>/_versions/<NAME-WITHOUT-EXT>/<NAME-WITHOUT-EXT>.YYYYMMDD-HHMMSS.h`
- Can be used in **2 ways**:
  1) As a **PlatformIO pre-script** (in `platformio.ini`):
       extra_scripts = pre:pio_scripts/pio_pull_headers.py
     (in this mode, options are read from PIO_* environment variables exported by the wrapper)
  2) **Through the CLI** (in the pipeline or terminal):
       python utils/pio_pull_headers.py --project-dir firmwares/Env/... \
         --runs-base trainings/environment/header_generator \
         --selector latest \
         --header-sources "environment_model_data.h, include/*.h" \
         --dst-dir models --versioning 1

📦 Environment variables used in PlatformIO mode (pre-script)
- PIO_MODEL_SELECTOR      : latest | vNNN | tsYYYYMMDD-HHMMSS | path | -N  (default: latest)
- PIO_RUNS_BASE           : run base (repository-relative paths are accepted). Example: trainings/.../header_generator or .../run
- PIO_HEADER_SOURCES      : list separated by , or ;  (example: "model.h, include/*.h")
- PIO_HEADER_DSTS         : 1-to-1 destinations relative to include/ (example: "models/model.h, drivers/x.h")
- PIO_HEADER_DST_DIR      : base subfolder under include/ for all files (example: "models")
- PIO_HEADER_SOURCE       : (LEGACY) one source header
- PIO_HEADER_DST          : (LEGACY) one destination under include/ (default: "model_data.h")
- PIO_HEADER_VERSIONING   : 1|0 enables/disables snapshots (default: 1)

🧠 Versioning note
- .models/headers is no longer used. Snapshots are stored **next to** the destination:
   include/<destination-subdir>/_versions/<stem>/<stem>.<timestamp>.h
- Example: destination = include/models/environment_model_data.h
           snapshots under: include/models/_versions/environment_model_data/environment_model_data.20250825-174210.h

🔁 Content-based recompilation (MD5)
- When running as a pre-script, the file enables `env.Decider("MD5")` so that header-content
  changes force a rebuild even when timestamps do not change.

"""

from __future__ import annotations
import os, sys, argparse, json, re, fnmatch, shutil
from pathlib import Path
from datetime import datetime


def _fs_path(p: Path | str) -> str:
    """Normalize a path for filesystem access, including long-path support on Windows."""
    s = str(Path(p))
    if os.name != "nt":
        return s
    if s.startswith("\\\\?\\"):
        return s
    if s.startswith("\\\\"):
        return "\\\\?\\UNC\\" + s[2:]
    return "\\\\?\\" + s


# =========================
# Repository discovery
# =========================

def find_repo_root() -> Path:
    env_root = os.environ.get("RUNNER_PROJECT_ROOT")
    if env_root:
        return Path(env_root).resolve()
    here = Path(__file__).resolve()
    for base in [here, *here.parents, Path.cwd(), *Path.cwd().parents]:
        if (base / "utils").exists():
            return base
    return Path.cwd()


REPO_ROOT = find_repo_root()
RUNS_BASE_DEFAULT = REPO_ROOT / "trainings" / "environment" / "header_generator" / "run"


# =========================
# Utils
# =========================

def _bool(s, default=False):
    if s is None:
        return default
    return str(s).lower() in {"1", "true", "yes", "on"}

def _split_list(s: str):
    if not s:
        return []
    return [p.strip() for p in re.split(r"[;,]", s) if p.strip()]

def list_runs(base: Path):
    runs = [d for d in Path(base).glob("run.*") if d.is_dir()]
    runs.sort(key=lambda d: d.stat().st_mtime, reverse=True)
    return runs

def normalize_runs_base(base: Path) -> Path:
    """Accept a 'flat' base without run.* entries. If a 'run' subfolder exists, try to use it."""
    p = base if base.is_absolute() else (REPO_ROOT / base).resolve()
    if (p / "latest").exists() or list_runs(p):
        return p
    if (p / "run").exists():
        q = (p / "run").resolve()
        if (q / "latest").exists() or list_runs(q):
            return q
    return p

def try_flat_base(run_base: Path, want_files: list[str]) -> Path | None:
    """If no run.* entry exists, verify recursively whether the requested files exist directly under the base."""
    if not want_files:
        return None
    present = set()
    all_h = list(run_base.rglob("*.h"))
    by_name = {}
    for p in all_h:
        by_name.setdefault(p.name, []).append(p)
    for name in want_files:
        if (run_base / name).exists() or name in by_name:
            present.add(name)
    return run_base if len(present) == len(want_files) else None

def resolve_run(base: Path, selector: str) -> Path:
    """Resolve a run from the normalized base."""
    base = normalize_runs_base(Path(base))

    if selector in ("", None, "latest"):
        latest = base / "latest"
        if latest.exists():
            return latest.resolve()
        runs = list_runs(base)
        if runs:
            return runs[0].resolve()
        raise FileNotFoundError(f"[resolve_run] No run.* entry found under {base}")

    p = Path(selector)
    if p.exists():
        return p.resolve()

    cand = base / selector
    if cand.exists():
        return cand.resolve()

    if selector.startswith(("v", "ts")):
        cand = base / f"run.{selector}"
        if cand.exists():
            return cand.resolve()

    if re.fullmatch(r"-\d+", str(selector)):
        idx = int(selector[1:])
        runs = list_runs(base)
        if 0 <= idx < len(runs):
            return runs[idx].resolve()
        raise FileNotFoundError(f"[resolve_run] Index {selector} is outside the valid range (runs={len(runs)})")

    raise FileNotFoundError(f"[resolve_run] Selector '{selector}' could not be resolved under {base}")

def expand_sources(run_dir: Path, specs_str: str):
    """Expand patterns/names into existing .h files under run_dir."""
    specs = _split_list(specs_str)
    if not specs:
        return []
    out = []
    for spec in specs:
        parent = (run_dir / spec).parent
        namepat = (run_dir / spec).name
        matches = []
        if any(ch in namepat for ch in "*?[]"):
            if parent.exists():
                for p in parent.rglob("*"):
                    if p.is_file() and fnmatch.fnmatch(p.name, namepat) and p.suffix.lower() == ".h":
                        matches.append(p)
        else:
            p = run_dir / spec
            if p.exists() and p.is_file() and p.suffix.lower() == ".h":
                matches.append(p)
        if not matches:
            print(f"[pull] WARN: Pattern/file not found: {spec}")
        else:
            for m in matches:
                if m not in out:
                    out.append(m.resolve())
    return out

def compute_dest_paths(include_dir: Path, src_list, dst_dir_rel: str, dst_names_str: str):
    """Calculate destinations for each source. Use dst_names[i] or the source basename."""
    dst_names = _split_list(dst_names_str)
    dst_dir_rel = (dst_dir_rel or "").replace("\\", "/").strip("/")
    base_dir = include_dir / dst_dir_rel if dst_dir_rel else include_dir
    base_dir.mkdir(parents=True, exist_ok=True)
    dests = []
    for i, src in enumerate(src_list):
        name = dst_names[i] if i < len(dst_names) and dst_names[i] else src.name
        dests.append(base_dir / name)
    return dests

def pick_header_single(run_dir: Path, source_name: str):
    """Legacy single-file mode: select one header."""
    if source_name:
        hp = run_dir / source_name
        if hp.exists():
            return hp.resolve()
        hits = list(run_dir.rglob(source_name))
        if hits:
            return hits[0].resolve()
        hs = sorted(run_dir.rglob("*.h"))
        listing = "\n".join(str(h) for h in hs[:30]) if hs else "(no .h files)"
        raise FileNotFoundError(
            f"Header not found: {hp}\n"
            f"Available under {run_dir}:\n{listing}\n"
            f"Tip: provide the correct relative path, for example: 'include/model_data.h'."
        )
    for c in [run_dir/"model_data.h", run_dir/"environment_model_data.h", run_dir/"environment_quantized_model.h"]:
        if c.exists():
            return c.resolve()
    hs = sorted(run_dir.rglob("*.h"))
    if hs:
        hs.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        return hs[0].resolve()
    raise FileNotFoundError(f"No .h file found under {run_dir}")

def save_version_snapshot(out_header: Path, src_path: Path, run_key: str):
    """
    Save a snapshot next to the destination:
      include/<subfolder>/_versions/<stem>/<stem>.<timestamp>.h
    Also maintain a small JSON manifest under:
      include/<subfolder>/_versions/<stem>/_manifest.json
    """
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    stem = out_header.stem
    vdir = out_header.parent / "_versions" / stem
    vdir.mkdir(parents=True, exist_ok=True)

    # Immutable snapshot
    snap = vdir / f"{stem}.{ts}.h"
    shutil.copy2(_fs_path(src_path), _fs_path(snap))

    # Manifest
    manifest = vdir / "_manifest.json"
    entry = {
        "copied_at": ts,
        "run": run_key,
        "src": str(src_path),
        "dst": str(out_header),
        "snapshot": str(snap),
    }
    try:
        data = []
        if manifest.exists():
            data = json.loads(manifest.read_text(encoding="utf-8") or "[]")
        data.append(entry)
        manifest.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    except Exception as e:
        print(f"[pull] WARN: Failed to update the manifest: {e}")

def do_pull(project_dir: Path,
            runs_base_in: str | Path,
            selector: str,
            header_sources: str,
            header_dsts: str,
            dst_dir: str,
            header_source: str,
            header_dst: str,
            versioning: bool) -> int:

    include_dir = project_dir / "include"
    include_dir.mkdir(parents=True, exist_ok=True)

    runs_base = normalize_runs_base(Path(runs_base_in))
    print(f"[pull] REPO_ROOT = {REPO_ROOT}")
    print(f"[pull] FW_ROOT   = {project_dir}")
    print(f"[pull] include/  = {include_dir}")
    print(f"[pull] RUNS_BASE = {runs_base}")
    print(f"[pull] SELECTOR  = {selector}")

    # Resolve the run (or flat base)
    try:
        run_dir = resolve_run(runs_base, selector)
        print(f"[pull] Resolved run: {run_dir}")
    except FileNotFoundError:
        wants = []
        if header_sources:
            wants.extend([Path(s).name for s in _split_list(header_sources)])
        if header_source:
            wants.append(Path(header_source).name)
        flat = try_flat_base(runs_base, wants)
        if flat is None:
            raise
        run_dir = flat
        print(f"[pull] ⚠️ Flat base detected. Using: {run_dir} (selector ignored).")

    run_key = run_dir.name

    # MULTI-FILE MODE
    src_list = expand_sources(run_dir, header_sources)
    if src_list:
        dest_list = compute_dest_paths(include_dir, src_list, dst_dir, header_dsts)
        for s, d in zip(src_list, dest_list):
            d.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(s, d)
            print(f"[pull] Copied: {s} -> {d}")
            if versioning:
                save_version_snapshot(d, s, run_key)
        if not versioning:
            print("[pull] Versioning disabled (--versioning=0)")
        return 0

    # SINGLE-FILE MODE
    src = pick_header_single(run_dir, header_source)

    dst_dir_norm = (dst_dir or "").replace("\\", "/").strip("/")
    header_dst_norm = (header_dst or "model_data.h").replace("\\", "/").strip("/")

    # Preserve a subfolder already present in header_dst.
    # When only a filename is provided and dst_dir exists, place it under include/dst_dir.
    if "/" in header_dst_norm:
        out = include_dir / header_dst_norm
    elif dst_dir_norm:
        out = include_dir / dst_dir_norm / header_dst_norm
    else:
        out = include_dir / header_dst_norm

    out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, out)
    print(f"[pull] Header: {src.name}")
    print(f"[pull] Copied: {src} -> {out}")
    if versioning:
        save_version_snapshot(out, src, run_key)
    else:
        print("[pull] Versioning disabled (--versioning=0)")
    return 0


# =========================
# CLI mode
# =========================

def _cli_main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Copy .h headers into include/ and save per-folder snapshots (CLI or PlatformIO pre-script)")
    ap.add_argument("--project-dir","-d", default="firmwares", help="PlatformIO project root containing include/")
    ap.add_argument("--runs-base", help="Run base (repository-relative paths are accepted). Example: trainings/.../header_generator ou .../run")
    ap.add_argument("--selector", default="latest", help="latest | vNNN | tsYYYY... | path | -N")
    # multi
    ap.add_argument("--header-sources", help="Source list separated by , or ; (example: 'model.h, include/*.h')")
    ap.add_argument("--header-dsts",    help="1-to-1 list of destinations relative to include/")
    ap.add_argument("--dst-dir",        help="Subfolder under include/ for all files (example: 'models')")
    # Single-file mode (legacy)
    ap.add_argument("--header-source",  help="One source header relative to the run")
    ap.add_argument("--header-dst",     default="model_data.h", help="One destination under include/")
    # Versioning
    ap.add_argument("--versioning", default="1", help="1|0 enables/disables snapshots")
    args = ap.parse_args(argv)

    proj = Path(args.project_dir)
    project_dir = (REPO_ROOT / proj).resolve() if not proj.is_absolute() else proj.resolve()
    runs_base = args.runs_base or str(RUNS_BASE_DEFAULT)

    return do_pull(
        project_dir=project_dir,
        runs_base_in=runs_base,
        selector=args.selector,
        header_sources=args.header_sources or "",
        header_dsts=args.header_dsts or "",
        dst_dir=args.dst_dir or "",
        header_source=args.header_source or "",
        header_dst=args.header_dst or "model_data.h",
        versioning=_bool(args.versioning, True),
    )


# =========================
# PlatformIO mode (pre-script)
# =========================

def _pio_before_build(source, target, env):
    """
    Hook called by PlatformIO before the build.
    Read PIO_* options from the environment.
    Enable env.Decider('MD5') to rebuild according to the content hash.
    """
    try:
        env.Decider("MD5")
        print("[pull] SCons Decider = MD5 (rebuild by content).")
    except Exception as e:
        print(f"[pull] WARN: could not set Decider('MD5'): {e}")

    project_dir = Path(env.subst("$PROJECT_DIR")).resolve()

    selector     = os.environ.get("PIO_MODEL_SELECTOR", "latest")
    runs_base_in = os.environ.get("PIO_RUNS_BASE", str(RUNS_BASE_DEFAULT))

    return do_pull(
        project_dir=project_dir,
        runs_base_in=runs_base_in,
        selector=selector,
        header_sources=os.environ.get("PIO_HEADER_SOURCES", ""),
        header_dsts=os.environ.get("PIO_HEADER_DSTS", ""),
        dst_dir=os.environ.get("PIO_HEADER_DST_DIR", ""),
        header_source=os.environ.get("PIO_HEADER_SOURCE", ""),
        header_dst=os.environ.get("PIO_HEADER_DST", "model_data.h"),
        versioning=_bool(os.environ.get("PIO_HEADER_VERSIONING","1"), True),
    )


# When running inside PIO/SCons, register the hook as a pre-action
try:
    # Import the SCons environment when available
    Import("env")  # type: ignore[name-defined]
    env.AddPreAction("buildprog", _pio_before_build)  # type: ignore[name-defined]
except Exception:
    # Outside SCons/PIO: use the standard CLI path
    pass


if __name__ == "__main__":
    raise SystemExit(_cli_main())
