#pragma once
// Auto-generated by LiteML-Edge scaler exporter.
//
// Feature order (MUST match firmware window packing):
// T_out, H_out, T_in_lag1, H_in_lag1, T_out_lag1, H_out_lag1, T_in_lag2, H_in_lag2, sin_hour, cos_hour, weekday, month
//
// Model output contract (RESIDUAL):
//   out[0] = ΔT_in
//   out[1] = ΔH_in
//
// MCU post-processing (contract):
//   Δ = inverse_scaler_y(out)
//   Tin = Tin_lag1 + ΔT_in
//   Hin = Hin_lag1 + ΔH_in
//

static const int   K_NUM_FEATURES = 12;
static const float X_MIN[12] = {21.110001, 43.0, 24.360001, 60.620712, 21.110001, 43.0, 24.360001, 60.620712, -1.0, -1.0, 0.0, 1.0};
static const float X_MAX[12] = {35.0, 100.0, 28.68, 75.301254, 35.0, 100.0, 28.68, 75.301254, 1.0, 1.0, 6.0, 12.0};

// MinMax feature_range for X normalization (if used on MCU)
static const float X_FEATURE_RANGE_LO = 0.000000f;
static const float X_FEATURE_RANGE_HI = 1.000000f;

static const int   K_NUM_TARGETS = 2;

// Y scaler is RESIDUAL bounds (Δ), order: ΔT_in, ΔH_in
static const float DY_MIN[2] = {-1.11, -0.747992};
static const float DY_MAX[2] = {0.91, 0.649111};

// MinMax feature_range for Y(Δ) inverse (if used on MCU)
static const float Y_FEATURE_RANGE_LO = 0.000000f;
static const float Y_FEATURE_RANGE_HI = 1.000000f;

// Helpful indices (avoid accidental swaps)
#define IDX_T 0
#define IDX_H 1
